// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1548406555);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1598963342);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1598963358);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1548406688);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 706);
user_pref("browser.cache.disk.capacity", 10240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1548406496);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{32e1f4ed-37cb-4f2b-ae83-8b670343f1f9}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1548370800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1598963802");
user_pref("browser.slowStartup.averageTime", 6439);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://ondemand.questionmark.eu/home/610110/user");
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1598963801);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1548406499933");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200708170202");
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.showMismatchUI", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"97d90306-c8f7-4501-a090-b27063bd90b8\",\"screenshots@mozilla.org\":\"60a5b3d2-e8c9-4e7a-ba9b-c6773c5ffa4d\",\"webcompat-reporter@mozilla.org\":\"06031973-88b3-43c2-8059-d0bd0afa46a3\",\"webcompat@mozilla.org\":\"dc82c77f-ecad-4e03-a2f9-75bd7774643f\",\"doh-rollout@mozilla.org\":\"7c2e18aa-9c03-4866-874d-f31d4c750d76\",\"default-theme@mozilla.org\":\"f0a6fe11-cd7c-43b9-8bbb-37cdfda8b54b\",\"google@search.mozilla.org\":\"b9db6963-9ae9-4888-bcc8-5d9fbbbef35f\",\"bing@search.mozilla.org\":\"7e2af21e-326c-4cc8-a585-9c9fa64372f6\",\"amazon@search.mozilla.org\":\"f5cf75b9-df04-4d96-99df-b644a61fde48\",\"ddg@search.mozilla.org\":\"7d6d34d9-e45c-403e-8c94-a7b9a2a61573\",\"ebay@search.mozilla.org\":\"ca56aedf-e414-4856-8fae-58e1fcaade83\",\"wikipedia@search.mozilla.org\":\"86193420-6c69-4029-9a21-550f0044e2fc\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20181207224003");
user_pref("media.gmp-manager.lastCheck", 1548406836);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.flash.arch", "x86_64-gcc3");
user_pref("plugin.flash.blockliststate", 0);
user_pref("plugin.flash.desc", "Shockwave Flash 0.0 r0");
user_pref("plugin.flash.lastmod_hi", 356);
user_pref("plugin.flash.lastmod_lo", -1546284672);
user_pref("plugin.flash.path", "/usr/lib/browser-plugin-freshplayer-pepperflash/libfreshwrapper-flashplayer.so");
user_pref("plugin.flash.version", "0.0.0.0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "7e99f49f-f159-46b7-b041-fb7fc9aa0cfb");
user_pref("security.sandbox.plugin.tempDirSuffix", "8fcb3300-0de1-48d9-9c50-7d2608eae64a");
user_pref("security.tls.version.min", 1);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1598963796);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
