version: "3.7"
name: "livenet"

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    env_file: ".env"
    #container_name: livenet-server
    privileged: true
    #init: true
    stop_signal: SIGTERM
    build:
      context: ./src
    ports:
      - 8095:8095
      - 69:69/udp
    #network_mode: host
    # networks:
    #   livenet:
    #     ipv4_address: ${SERVER_IP}
    volumes:
      #- ${TFTP_DIR}:/srv/tftp
      - ${NFS_DIR}:/nfs
      - ./root:/root
      - ./etc/exports:/etc/exports
      - ./etc/default/nfs-kernel-server:/etc/default/nfs-kernel-server
      - ./etc/default/isc-dhcp-server:/etc/default/isc-dhcp-server
      - ./etc/default/tftpd-hpa:/etc/default/tftpd-hpa
      - ./etc/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./etc/network/interfaces:/etc/network/interfaces
      - ./pxelinux.cfg:/tftp/pxelinux.cfg
      - /dev/log:/dev/log
    # cap_add:
    #   - NET_ADMIN

networks:
  livenet:
    #external: true
    driver: macvlan
    driver_opts:
      parent: ${BRIDGE}
      macvlan_mode: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.22.0/24
          ip_range: 10.1.22.64/26
          gateway: ${GATEWAY}
