# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  LIST: ./scripts/detect_distro.sh
  NFSD_TEST: ./scripts/nfsd_test.sh

dotenv: [".env"]

tasks:
  default:
    cmds:
      - bash {{ .LIST }}
    silent: true
  
  build:
    desc: "build docker image"
    cmds:
      #- docker build --rm --compress -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./src
      - docker compose build
  
  start:
    desc: Start the service
    cmds:
      - bash {{ .NFSD_TEST }} 
      - docker compose up


  network:
    desc: create livenet network
    cmds:
      - |
        sudo ip link add name ${BRIDGE} type bridge
        sudo ip link set dev ${BRIDGE} up
        sudo ip addr add ${GATEWAY}/24 dev ${BRIDGE}
        #echo 1 > /proc/sys/net/ipv4/ip_forward
        sudo iptables -t nat -A POSTROUTING -o ${BRIDGE} -j MASQUERADE
    status:
      - ip link show ${BRIDGE}

  network:down:
    cmds:
      - sudo ip link del name ${BRIDGE}

  cli:
    desc: cli 
    cmds:
      - docker compose run --rm -it server bash

  vm:
    cmds:
      - qemu-system-x86_64 -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=br-livenet,id=net0 -boot n -bios /usr/share/ovmf/x64/OVMF.fd
