#!/bin/sh

# go on 
set +e

cd /usr/share/libpam-script/close.d

for s in *; do
	[ -x ${s} ] || continue
	./${s}    
done

stamp=`/bin/date +'%Y%m%d%H%M%S %a'`
logger -t "PAM SCRIPT SESS CLOSE"  " $stamp $PAM_SERVICE $PAM_TYPE user=$PAM_USER tty=$PAM_TTY"

exit 0

