#!/bin/sh -e
# initramfs hook for livenet

#set -x
PREREQ=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQ"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

# Funzioni di supporto (package: initramfs-tools-core), ad esempio copy_exec
. /usr/share/initramfs-tools/hook-functions

# ${DESTDIR} è una variabile esportata da mkinitramfs
# è il percorso della radice della nuova initramfs
rm ${DESTDIR}/bin/cpio # importante! altrimenti rimane un cpio troppo semplificato


# funzione che copia un binario nell'immagine, assicurandosi che vi siano anche tutte le librerie necessarie.
copy_exec /bin/cpio /bin

mkdir -p ${DESTDIR}/conf
cp /etc/livenet/livenet.conf ${DESTDIR}/conf
[ -f /etc/livenet/livenet.conf.override ] && cp /etc/livenet/livenet.conf.override ${DESTDIR}/conf
cp /etc/initramfs-tools/scripts/functions-livenet ${DESTDIR}/conf

manual_add_modules overlay
auto_add_modules net

# pulizia di firmware non necessario e pesante
set +e
rm -f ${DESTDIR}/lib/firmware/* >/dev/null 2>&1
set -e

### qui sotto andrebbe commentato in produzione ###

# tastiera italiana in initram
# attivata da do_debug_shell (loadkeys /etc/boottime.kmap.gz)
#cp -au /etc/console-setup/cached.kmap.gz ${DESTDIR}/etc/boottime.kmap.gz

# nfs4
echo nobody::65534:65534::/:/usr/bin/nologin >> ${DESTDIR}/etc/passwd
echo nobody::65534: >> ${DESTDIR}/etc/group
copy_exec /usr/sbin/rpc.idmapd /bin
copy_exec /sbin/mount.nfs /bin
mkdir -p ${DESTDIR}/usr/lib/x86_64-linux-gnu/libnfsidmap
cp -au /usr/lib/x86_64-linux-gnu/libnfsidmap/nsswitch.so ${DESTDIR}/usr/lib/x86_64-linux-gnu/libnfsidmap
cp -au /etc/netconfig ${DESTDIR}/etc/netconfig
mkdir -p ${DESTDIR}/var/lib/nfs/rpc_pipefs/ 

# Se vuoi inviare i log al server rsyslog
copy_exec /usr/bin/logger /bin

# debug purpose ################
# ricordati di mettere FRAMEBUFFER=n in /etc/initramfs-tools/conf.d/splash
copy_exec /sbin/lsmod /bin
copy_exec /usr/bin/ping /bin
copy_exec /usr/bin/strace /bin
#################################
