version: "3"
name: livenet

services:
  lnode:
    image: livener/node
    container_name: lnode
    build:
      context: .
    privileged: true
    volumes:
      # solo durante sviluppo
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      #- ./docker/exports:/etc/exports
      #### pxe
      - ./runtime/bash_history:/root/.bash_history
      - ./overlay/etc/default/tftpd-hpa:/etc/default/tftpd-hpa
      - ./overlay/boot/pxelinux.cfg:/boot/bios/pxelinux.cfg
      - ./overlay/boot/grub.cfg:/boot/grub-node/grub.cfg
      - /dev/log:/dev/log
      #### releases
      - ./releases:/mnt/releases
      #### node
      - ./overlay/usr/bin/ln-client:/usr/bin/ln-client
      # - ./overlay/etc/livenet:/etc/livenet
      # - ./overlay/etc/initramfs-tools/conf.d:/etc/initramfs-tools/conf.d
      # - ./overlay/etc/initramfs-tools/hooks:/etc/initramfs-tools/hooks
      # - ./overlay/etc/initramfs-tools/scripts/functions-livenet:/etc/initramfs-tools/scripts/functions-livenet
      # - ./overlay/etc/initramfs-tools/scripts/livenet:/etc/initramfs-tools/scripts/livenet
      # - ./overlay/etc/initramfs-tools/scripts/livenet-bottom:/etc/initramfs-tools/scripts/livenet-bottom
      # - ./overlay/etc/initramfs-tools/scripts/livenet-top:/etc/initramfs-tools/scripts/livenet-top
      # - ./overlay/usr/sbin/ln-mng:/usr/sbin/ln-mng
      # - ./overlay/usr/sbin/policy-rc.d:/usr/sbin/policy-rc.d
    #ports:
    #   - 2049:2049
    #networks:
    #  - livenet_macvlan
    network_mode: host

# networks:
#   livenet_macvlan:
#     external: true
