version: "3"

services:
  lnode:
    image: livener/node
    container_name: lnode
    build:
      context: .
    privileged: true
    volumes:
      # solo durante sviluppo
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      #- ./docker/exports:/etc/exports
      #### pxe
      - ./runtime/bash_history:/root/.bash_history
      - ./overlay/etc/default/tftpd-hpa:/etc/default/tftpd-hpa
      - ./overlay/tftp/pxelinux.cfg:/tftp/bios/pxelinux.cfg
      - ./overlay/tftp/grub.cfg:/tftp/grub/grub.cfg
      - /dev/log:/dev/log
      #### node
      - ./overlay/etc/livenet:/etc/livenet
      - ./overlay/etc/initramfs-tools/conf.d:/etc/initramfs-tools/conf.d
      - ./overlay/etc/initramfs-tools/hooks:/etc/initramfs-tools/hooks
      - ./overlay/etc/initramfs-tools/scripts/functions-livenet:/etc/initramfs-tools/scripts/functions-livenet
      - ./overlay/etc/initramfs-tools/scripts/livenet:/etc/initramfs-tools/scripts/livenet
      - ./overlay/etc/initramfs-tools/scripts/livenet-bottom:/etc/initramfs-tools/scripts/livenet-bottom
      - ./overlay/etc/initramfs-tools/scripts/livenet-top:/etc/initramfs-tools/scripts/livenet-top
      - ./overlay/usr/sbin/ln-mng:/usr/sbin/ln-mng
      - ./overlay/usr/sbin/policy-rc.d:/usr/sbin/policy-rc.d
    ports:
      - 2049:2049
      #- 20048:20048
    networks:
      - livenet_macvlan

networks:
  livenet_macvlan:
    external: true
