# https://taskfile.dev

version: '3'

dotenv: [".env"]

tasks:
  default:
    cmds:
      - go-task -l
    silent: true

  build:
    desc: build li
    cmds:
      - |
        BUILDKIT_PROGRESS=plain ${_compose} build 
      - sudo rm -f releases/*
      #- docker export $(docker create ${IMAGE}) --output="livenet.tar"

  start:
    cmds:
      - mkdir -p runtime releases
      - touch runtime/bash_history
      - ${_compose} up -d --remove-orphans

  logs:
    cmds:
      - sudo journalctl -f

  cli:
    cmds:
      - ${_compose} exec lnode bash        

  ssh:
    desc: "connect to client node"
    cmds:
      - ssh root@192.168.124.18

  diff:
    cmds:
      - ${_docker} diff ${NODE}

  commit:
    desc: task commit -- 20230808.00
    cmds:
      - |
        ID=$(${_docker} container ls --all --quiet --no-trunc --filter "name=${NODE}")
        RELEASE={{.RELEASE}}
        [ -n "$RELEASE" ] || RELEASE={{.CLI_ARGS}}
        ${_docker} diff ${NODE} | ${_compose} exec -T lnode ln-mng --commit $RELEASE
        ${_docker} commit ${ID} livenet/node:${RELEASE}
        ${_compose} down 
        
        sed -i "s/VERSION=.*/VERSION=${RELEASE}/" .env
        docker-compose up -d
  
  release:
    cmds:
      - |
        RELEASE={{.RELEASE}}
        [ -n "$RELEASE" ] || RELEASE={{.CLI_ARGS}}
        ${_docker} export ${NODE} --output="releases/${RELEASE}-full.tar"
        pigz releases/${RELEASE}-full.tar

  destroy:
    cmds:
      - sudo rm -f releases/*
      - sed -i "s/VERSION=.*/VERSION=latest/" .env
      - ${_compose} down -t 60 || true
      - ${_docker} images | grep livenet/node | awk '{print $3}' | xargs ${_docker} rmi || true
      - rm -f runtime/vm.qcow2

  reset:
    cmds:
      - task: destroy
      - task: build
      - task: start
      - sleep 5
      - task: commit
        vars:
          RELEASE: 20230801.00
      - task: release
        vars:
          RELEASE: 20230801.00

  mount:
    cmds:
      - mkdir -p /tmp/test
      - sudo mount -t nfs -o vers=4,loud,retry=0,timeo=5 192.168.124.1:/ /tmp/test
      - ls /tmp/test
      - sudo umount /tmp/test

  network:
    desc: create livenet network
    cmds:
      - |
        sudo virsh net-info livenet && sudo virsh net-destroy livenet || true
        sudo virsh net-define libvirt/net-livenet.xml
        sudo virsh net-start livenet
        ${_compose} down

  vm:disk:
    cmds:
      - |
        [ -f ${DISK} ] || qemu-img create -f qcow2 -o preallocation=metadata ${DISK} 60G

  vm:bios:
    desc: "boot vm in uefi: see 4.3 on https://wiki.archlinux.org/title/QEMU"
    cmds:
      - task: vm:disk
      - |
        qemu-system-x86_64 -nographic -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=livenet,id=net0 \
          -drive id=vda,file=${DISK} \
          -boot n

  vm:spice:
    desc: "spice client"
    cmds:
      - sleep 1
      - spicy -h localhost -p 5910
  
  vm:bios:local:
    desc: "boot vm in uefi: see 4.3 on https://wiki.archlinux.org/title/QEMU"
    cmds:
      - task: vm:disk
      - |
        qemu-system-x86_64 -nographic -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=livenet,id=net0 \
          -spice port=5910,addr=0.0.0.0,disable-ticketing \
          -drive id=vda,file=${DISK} \
          -boot d
  
  vm:efi:local:
    desc: "boot vm in uefi: see 4.3 on https://wiki.archlinux.org/title/QEMU"
    cmds:
      - task: vm:disk
      - |
        qemu-system-x86_64 -nographic -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=livenet,id=net0 \
          -spice port=5910,addr=0.0.0.0,disable-ticketing \
          -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
          -drive if=pflash,format=raw,unit=1,file=/tmp/OVMF_VARS.fd \
          -drive id=vda,file=${DISK} \
          -boot d

  vm:
    desc: "boot local disk vm with spice client"
    deps: [vm:spice, vm:efi:local]


  vm:cd:
    desc: "boot systemrescuecd"
    cmds:
      - |
        [ -f runtime/systemrescue-10.01-amd64.iso ] || https://fastly-cdn.system-rescue.org/releases/10.01/systemrescue-10.01-amd64.iso
        qemu-system-x86_64 -nographic -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=livenet,id=net0 \
          -cdrom runtime/systemrescue-10.01-amd64.iso

  vm:efi:
    desc: "boot vm in uefi: see 4.3 on https://wiki.archlinux.org/title/QEMU"
    cmds:
      - task: vm:disk
      - |
        cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp/OVMF_VARS.fd
        qemu-system-x86_64 -smp 2 -m 2048 -enable-kvm -net nic,netdev=net0 -netdev bridge,br=livenet,id=net0 \
          -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
          -drive if=pflash,format=raw,unit=1,file=/tmp/OVMF_VARS.fd \
          -drive id=vda,file=${DISK} \
          -boot d
