# https://taskfile.dev

version: '3'

dotenv: [".env"]

tasks:
  default:
    cmds:
      - go-task -l
    silent: true

  build:
    desc: build li
    cmds:
      - BUILDKIT_PROGRESS=plain docker compose build 
      #- docker export $(docker create ${IMAGE}) --output="livenet.tar"

  start:
    cmds:
      - docker compose up -d
      #- docker run --name lnode -it -d -p 2049:2049 -p 20048:20048 ${IMAGE} || true

  cli:
    cmds:
      - docker compose exec lnode bash
      #- docker run --name lnode -it -d ${IMAGE} || true
      #- task: run
      #- docker exec -it ${NODE} bash

  diff:
    cmds:
      - docker diff ${NODE}

  commit:
    desc: task commit -- 0.2
    vars:
      Id: Id
    cmds:
      - |
        ID=$(docker container ls --all --quiet --no-trunc --filter "name=${NODE}")
        docker commit ${ID} livenet/node:{{.CLI_ARGS}}

  destroy:
    cmds:
      - docker compose down
      - docker images | grep livenet/node | awk '{print $3}' | xargs docker rmi
      #- docker container stop ${NODE} || true
      #- docker container rm ${NODE}


  mount:
    cmds:
      - mkdir -p /tmp/test
      - sudo mount -t nfs -o vers=4,loud localhost:/ /tmp/test
      - ls /tmp/test
      - sudo umount /tmp/test

  kernel:copy:
    cmds:
      - docker cp lnode:/boot/initrd.img-5.15.0-76-generic ../server/boot/jammy/initrd
      - docker cp lnode:/boot/vmlinuz-5.15.0-76-generic ../server/boot/jammy/kernel

