#!/bin/bash

TIME_NOW=$(date +%s)
TIMEOUT_NAC=15

#exec > /tmp/start 2>&1
#set -x

. /etc/livenet/livenet.conf

#set +e
logger -t "01_nac" "esecuzione... "
[ "${livenet_8021x}" = "true" ] || exit 0

# Provvisorio
logger -t "01_nac" "8021x abilitato. RIcerca utente ${PAM_USER}"

grep -q "^${PAM_USER}:" /etc/passwd
[ $? = 0 ] && exit 0 # local user, no NAC
# Provvisorio
logger -t "01_nac" "Utente ${PAM_USER} non locale "
WPACONF=/run/user/${PAM_USER}/wpa_supplicant.conf

for nic in /run/net-*.conf; do
	. ${nic}
done

if [ "${PAM_SERVICE}" = "login" ] || [ "${PAM_SERVICE}" = "gdm-password" ] || [ "${PAM_SERVICE}" = "lightdm" ]; then
    logger -t "01_nac" "Autenticazione per Servizio ${PAM_SERVICE}"
    if [ -f ${WPACONF} ]; then
#	systemctl stop autofs
        echo "802.1x enabled" | logger
        umount -lf ${HOME} >/dev/null 2>&1
#        dhclient -r ${DEVICE}
        ip addr flush dev  ${DEVICE}
        wpa_supplicant -B -c ${WPACONF} -D wired -i ${DEVICE} -W
        log_lightdm "AUTENTICAZIONE DI RETE"
        echo logoff | wpa_cli
        sleep 4
        echo logon | wpa_cli
        
        i=0 
        while [ 1 ]; do
            wpa_cli status | grep "EAP state" | grep SUCCESS
            if [ $? = 0 ]; then
                logger -t "01_nac" "Autenticazione utente ${PAM_USER} riuscita."
                break
            fi

            i=$((i+1))
            # Dopo il timeout recupera un ip nella rete di fallback
            if [ $i -gt ${TIMEOUT_NAC} ]; then
                echo "wpa_supplicant on interface ${DEVICE} died. Get a fallback address" | logger 

                killall wpa_supplicant
                ip addr flush dev  ${DEVICE}
                dhclient ${DEVICE}
                log_lightdm "AUTENTICAZIONE DI RETE FALLITA"
                logger -t "01_nac" "Autenticazione utente ${PAM_USER} fallita dopo $$(( $(date +%s) - $TIME_NOW )) seconds"
                # pam exit at login (see pam.d/common-session)
                exit 100
            fi
            echo "wpa_supplicant sleep" | logger 
            sleep 1
        done
        rm -f ${WPACONF}
        log_lightdm "ACQUISIZIONE INDIRIZZO IP ..."
        dhclient ${DEVICE}
        
        log_lightdm "ACQUISIZIONE IP RIUSCITA"
        sleep 1
#	systemctl start autofs
#	sleep 5
    fi
fi
logger -n ${SYSLOG_IP} -P ${SYSLOG_PORT} -t "01_nac" "Execution time: $(( $(date +%s) - $TIME_NOW )) seconds"
exit 0
