# https://taskfile.dev

version: '3'

dotenv: [".env"]

tasks:
  default:
    cmds:
      - go-task -l
    silent: true

  build:
    cmds:
      - docker build . -t ${IMAGE}
      - docker export $(docker create ${IMAGE}) --output="livenet.tar"

  cli:
    cmds:
      #- docker run --name ${IMAGE} -it ${IMAGE} bash
      - docker start ${IMAGE}
      - docker exec -it ${IMAGE} bash

  diff:
    cmds:
      - docker diff ${IMAGE}